name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t your-docker-image-name .

      - name: Push Docker image
        run: docker push your-docker-image-name

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
